spring:
  profiles:
    location: local
  datasource:
    username: postgres
    password: ENC(Bm/GUgfTbDQUGBgceLGrqA==)
    url:  jdbc:postgresql://localhost:5432/postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create