spring:
  profiles:
    location: ci
  datasource:
    username: postgres
    password: postgres
    url:  jdbc:postgresql://localhost:5432/postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create