on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: 005d9eb7-kr1-registry.container.cloud.toast.com/pickabook-server-prod
          username: ${{ secrets.NHN_USER_KEY }}
          password: ${{ secrets.NHN_SECRET_KEY }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            005d9eb7-kr1-registry.container.cloud.toast.com/pickabook-server-prod/${{ github.repository_owner }}/my-container-test:latest
            005d9eb7-kr1-registry.container.cloud.toast.com/pickabook-server-prod/${{ github.repository_owner }}/my-container-test:${{ env.RELEASE_VERSION }}